language: minimal

os:
  - linux
  - osx

# Multi-OS Miniconda install from https://github.com/gitter-lab/ssps/blob/master/.travis.yml
before_install:
  # Download OS-specific version of Miniconda installer
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-py37_4.8.2-Linux-x86_64.sh -O miniconda.sh
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-py37_4.8.2-MacOSX-x86_64.sh -O miniconda.sh
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source $HOME/miniconda/etc/profile.d/conda.sh
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  # Do not use a conda environment.yml file because there are few dependencies
  - conda create -n ppa python=3.6 numpy=1.19 networkx=2.4 requests=2.24
  - conda activate ppa

install:
  # Install pathway parameter advising
  - python setup.py install
  # Install PGD dependency
  # macOS has gcc as an alias for clang, so specifically set gcc
  # See https://docs.travis-ci.com/user/languages/c/#gcc-on-macos
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install gcc@10
      export CC=gcc-10
      export CXX=g++-10
    fi
  - cd bin
  - bash setupPGD.sh

script:
  # Run PPA examples
  - bash runPPA.sh ../data/Wnt wnt_ranking.txt ../lib/pgd/ 
  - bash runNetBoxIL2.sh
  # Compare the generated IL2 output with the reference output
  - cmp ../tests/reference/il2_ranking.txt il2_ranking.txt
