language: python
python:
  - "3.6"
# Only test on Python 3.6 initially
#  - "3.7"
#  - "3.8"
cache:
  - pip
install:
  - pip install networkx numpy 
script:
  - unzip referencePathways/reactome/reactomeGraphlets.zip
  - cd scripts
  - bash runNetBoxIL2.sh
