language: python
os:
  - linux
  - osx
python:
  - "3.6"
# Only test on Python 3.6 initially
#  - "3.7"
#  - "3.8"
cache:
  - pip
install:
  - pip install networkx numpy
script:
  - cd scripts
  # Installs pgd, uses graph conversion script, and runs PPA
  - bash runPPA.sh ../data/Wnt wnt_ranking.txt
  - bash runNetBoxIL2.sh
  # Compare the generated IL2 output with the reference output
  - cmp ../tests/reference/il2_ranking.txt il2_ranking.txt
